// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Retro Board Game

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void initGame(lv_event_t * e);
void togglePegColorCol1(lv_event_t * e);
void togglePegColorCol2(lv_event_t * e);
void togglePegColorCol3(lv_event_t * e);
void togglePegColorCol4(lv_event_t * e);
void CheckCode(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
