// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Retro Board Game

#ifndef UI_SCREEN_MAIN_H
#define UI_SCREEN_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Main
extern void ui_Screen_Main_screen_init(void);
extern void ui_Screen_Main_screen_destroy(void);
extern lv_obj_t *ui_Screen_Main;
extern void ui_event_Main_Button_restart( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_restart;
extern lv_obj_t *ui_Main_Label_Label1;
extern lv_obj_t *ui_Main_Container_time;
extern lv_obj_t *ui_Main_Label_timer0;
extern lv_obj_t *ui_Main_Label_timer1;
extern lv_obj_t *ui_Main_Container_row0;
extern lv_obj_t *ui_Main_Button_ans1;
extern lv_obj_t *ui_Main_Button_ans2;
extern lv_obj_t *ui_Main_Button_ans3;
extern lv_obj_t *ui_Main_Button_ans4;
extern lv_obj_t *ui_Main_Label_binder;
extern lv_obj_t *ui_Main_Container_row1;
extern void ui_event_Main_Button_peg1( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg1;
extern void ui_event_Main_Button_peg2( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg2;
extern void ui_event_Main_Button_peg3( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg3;
extern void ui_event_Main_Button_peg4( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg4;
extern lv_obj_t *ui_Main_Button_pt1;
extern lv_obj_t *ui_Main_Button_pt2;
extern lv_obj_t *ui_Main_Button_pt3;
extern lv_obj_t *ui_Main_Button_pt4;
extern void ui_event_Main_Checkbox_Checkbox1( lv_event_t * e);
extern lv_obj_t *ui_Main_Checkbox_Checkbox1;
extern lv_obj_t *ui_Main_Container_row2;
extern void ui_event_Main_Button_peg5( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg5;
extern void ui_event_Main_Button_peg6( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg6;
extern void ui_event_Main_Button_peg7( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg7;
extern void ui_event_Main_Button_peg8( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg8;
extern lv_obj_t *ui_Main_Button_pt5;
extern lv_obj_t *ui_Main_Button_pt6;
extern lv_obj_t *ui_Main_Button_pt7;
extern lv_obj_t *ui_Main_Button_pt8;
extern void ui_event_Main_Checkbox_Checkbox2( lv_event_t * e);
extern lv_obj_t *ui_Main_Checkbox_Checkbox2;
extern lv_obj_t *ui_Main_Container_row3;
extern void ui_event_Main_Button_peg9( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg9;
extern void ui_event_Main_Button_peg10( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg10;
extern void ui_event_Main_Button_peg11( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg11;
extern void ui_event_Main_Button_peg12( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg12;
extern lv_obj_t *ui_Main_Button_pt9;
extern lv_obj_t *ui_Main_Button_pt10;
extern lv_obj_t *ui_Main_Button_pt11;
extern lv_obj_t *ui_Main_Button_pt12;
extern void ui_event_Main_Checkbox_Checkbox3( lv_event_t * e);
extern lv_obj_t *ui_Main_Checkbox_Checkbox3;
extern lv_obj_t *ui_Main_Container_row4;
extern void ui_event_Main_Button_peg13( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg13;
extern void ui_event_Main_Button_peg14( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg14;
extern void ui_event_Main_Button_peg15( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg15;
extern void ui_event_Main_Button_peg16( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg16;
extern lv_obj_t *ui_Main_Button_pt13;
extern lv_obj_t *ui_Main_Button_pt14;
extern lv_obj_t *ui_Main_Button_pt15;
extern lv_obj_t *ui_Main_Button_pt16;
extern void ui_event_Main_Checkbox_Checkbox4( lv_event_t * e);
extern lv_obj_t *ui_Main_Checkbox_Checkbox4;
extern lv_obj_t *ui_Main_Container_row5;
extern void ui_event_Main_Button_peg17( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg17;
extern void ui_event_Main_Button_peg18( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg18;
extern void ui_event_Main_Button_peg19( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg19;
extern void ui_event_Main_Button_peg20( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg20;
extern lv_obj_t *ui_Main_Button_pt17;
extern lv_obj_t *ui_Main_Button_pt18;
extern lv_obj_t *ui_Main_Button_pt19;
extern lv_obj_t *ui_Main_Button_pt20;
extern void ui_event_Main_Checkbox_Checkbox5( lv_event_t * e);
extern lv_obj_t *ui_Main_Checkbox_Checkbox5;
extern lv_obj_t *ui_Main_Container_row6;
extern void ui_event_Main_Button_peg21( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg21;
extern void ui_event_Main_Button_peg22( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg22;
extern void ui_event_Main_Button_peg23( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg23;
extern void ui_event_Main_Button_peg24( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg24;
extern lv_obj_t *ui_Main_Button_pt21;
extern lv_obj_t *ui_Main_Button_pt22;
extern lv_obj_t *ui_Main_Button_pt23;
extern lv_obj_t *ui_Main_Button_pt24;
extern void ui_event_Main_Checkbox_Checkbox6( lv_event_t * e);
extern lv_obj_t *ui_Main_Checkbox_Checkbox6;
extern lv_obj_t *ui_Main_Container_row7;
extern void ui_event_Main_Button_peg25( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg25;
extern void ui_event_Main_Button_peg26( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg26;
extern void ui_event_Main_Button_peg27( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg27;
extern void ui_event_Main_Button_peg28( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg28;
extern lv_obj_t *ui_Main_Button_pt25;
extern lv_obj_t *ui_Main_Button_pt26;
extern lv_obj_t *ui_Main_Button_pt27;
extern lv_obj_t *ui_Main_Button_pt28;
extern void ui_event_Main_Checkbox_Checkbox7( lv_event_t * e);
extern lv_obj_t *ui_Main_Checkbox_Checkbox7;
extern lv_obj_t *ui_Main_Container_row8;
extern void ui_event_Main_Button_peg29( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg29;
extern void ui_event_Main_Button_peg30( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg30;
extern void ui_event_Main_Button_peg31( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg31;
extern void ui_event_Main_Button_peg32( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg32;
extern lv_obj_t *ui_Main_Button_pt29;
extern lv_obj_t *ui_Main_Button_pt30;
extern lv_obj_t *ui_Main_Button_pt31;
extern lv_obj_t *ui_Main_Button_pt32;
extern void ui_event_Main_Checkbox_Checkbox8( lv_event_t * e);
extern lv_obj_t *ui_Main_Checkbox_Checkbox8;
extern lv_obj_t *ui_Main_Container_row9;
extern void ui_event_Main_Button_peg33( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg33;
extern void ui_event_Main_Button_peg34( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg34;
extern void ui_event_Main_Button_peg35( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg35;
extern void ui_event_Main_Button_peg36( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg36;
extern lv_obj_t *ui_Main_Button_pt33;
extern lv_obj_t *ui_Main_Button_pt34;
extern lv_obj_t *ui_Main_Button_pt35;
extern lv_obj_t *ui_Main_Button_pt36;
extern void ui_event_Main_Checkbox_Checkbox9( lv_event_t * e);
extern lv_obj_t *ui_Main_Checkbox_Checkbox9;
extern lv_obj_t *ui_Main_Container_row10;
extern void ui_event_Main_Button_peg37( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg37;
extern void ui_event_Main_Button_peg38( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg38;
extern void ui_event_Main_Button_peg39( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg39;
extern void ui_event_Main_Button_peg40( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg40;
extern lv_obj_t *ui_Main_Button_pt37;
extern lv_obj_t *ui_Main_Button_pt38;
extern lv_obj_t *ui_Main_Button_pt39;
extern lv_obj_t *ui_Main_Button_pt40;
extern void ui_event_Main_Checkbox_Checkbox10( lv_event_t * e);
extern lv_obj_t *ui_Main_Checkbox_Checkbox10;
extern lv_obj_t *ui_Main_Container_row11;
extern void ui_event_Main_Button_peg41( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg41;
extern void ui_event_Main_Button_peg42( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg42;
extern void ui_event_Main_Button_peg43( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg43;
extern void ui_event_Main_Button_peg44( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg44;
extern lv_obj_t *ui_Main_Button_pt41;
extern lv_obj_t *ui_Main_Button_pt42;
extern lv_obj_t *ui_Main_Button_pt43;
extern lv_obj_t *ui_Main_Button_pt44;
extern void ui_event_Main_Checkbox_Checkbox11( lv_event_t * e);
extern lv_obj_t *ui_Main_Checkbox_Checkbox11;
extern lv_obj_t *ui_Main_Container_row12;
extern void ui_event_Main_Button_peg45( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg45;
extern void ui_event_Main_Button_peg46( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg46;
extern void ui_event_Main_Button_peg47( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg47;
extern void ui_event_Main_Button_peg48( lv_event_t * e);
extern lv_obj_t *ui_Main_Button_peg48;
extern lv_obj_t *ui_Main_Button_pt45;
extern lv_obj_t *ui_Main_Button_pt46;
extern lv_obj_t *ui_Main_Button_pt47;
extern lv_obj_t *ui_Main_Button_pt48;
extern void ui_event_Main_Checkbox_Checkbox12( lv_event_t * e);
extern lv_obj_t *ui_Main_Checkbox_Checkbox12;
extern lv_obj_t *ui_Main_Label_vaandcob;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

